<?php
/**
 * User: execut
 * Date: 16.06.16
 * Time: 17:22
 */

namespace execut\moduleTemplate;


class Module extends \yii\base\Module
{
    public $controllerNamespace = 'execut\moduleTemplate\controllers';
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}